name: electric_meter_bill
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  get_it: ^7.6.4
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  archive: ^3.4.9
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  file_selector: ^1.0.1
  flutter_email_sender: ^6.0.2
  pdf: ^3.10.7
  open_file: ^3.3.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
